import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import Styles from "@/styles/Home.module.css";

import HeroCarousel from "./component/herocarousel";
import Card from "./component/card";
import NavBar from "./component/nav";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavBar/>
        <HeroCarousel/> 
        {/* <div className={Styles.cardcarousel}>
        <Card/>
        <Card/>
        <Card/>
        <Card/>
        </div> */}
        
      </div>
    </>
  );
}
